### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by marcoscleison** [ahayashi/chapel-gpu#5]
Hi,
Congratulations on the amazing work.
I am suffering  some issues to compile an example:
```bash

CHPL_LOCALE_MODEL=gpu chpl --fast -M $CHPL_GPU_HOME/chapel-gpu/src vc.hybrid.chpl vc.gpu.o -lcudart -lcuda
error: Type 'chpl_localeID_t' must be defined in the Chapel internal modules.
error: Type 'chpl_comm_on_bundle_t' must be defined in the Chapel internal modules.
error: Type 'chpl_task_bundle_t' must be defined in the Chapel internal modules.


```

My chapel is:
```bash
chpl version 1.20.0
Copyright (c) 2004-2019, Cray Inc.  (See LICENSE file for more details)
```
nvcc is:
```bash
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
I am using clang-3.9. I can compile Cuda 9 programs and works pretty well;

I am using ubuntu 18.04 LTS.
Can you give me some tips to solve such an issue?
Thanks.

**Comment by ahayashi** [comment]
Hello, @marcoscleison 

Thank you for opening this issue and sorry for the delay! Now I noticed your message.

Can you remove CHPL_LOCALE_MODEL=gpu because we don't use this feature in the current release (Please see https://github.com/ahayashi/chapel-gpu#how-to-use-the-gpuiterator for more details). If the problem still persists, can you try to use the provided Makefile like this?

```
$ cd apps/vector_copy
// for single node execution
$ make cudagpu
```

Another thing I'd like to see would be the output of `printchplenv`:
```
$ ${CHPL_HOME}/util/printchplenv
```
Can you paste the output if the CHPL_LOCALE_MODEL thing does not solve your problem?

Please let me know if you have any further questions.

**Comment by ahayashi** [comment]
Hi, @marcoscleison 

Just checking, do you still have the compilation problem?

Please let me know if I can be of any help.

**Comment by marcoscleison** [comment]
Hi, 
I am having problems with the compilation. It seems that some chapel runtime functions cannot be found. Let me investigate a little more. 
Any way. Thank you very much for the attention.

**Comment by ahayashi** [comment]
Hello, @marcoscleison 

Sure, please take your time to figure out what's going on!

Just FYI, here is an end-to-end sequence that I tested with the latest version of `chapel` and `chapel-gpu` repos today. I also confirmed that `CHPL_COMM=gasnet` also works. Hope that helps!

```
$ git clone https://github.com/chapel-lang/chapel.git
$ cd chapel
$ source ./util/setchplenv.sh 
$ ./util/printchplenv                                                                                                                                                                    [~/work/test/chapel]
machine info: Linux titanxp-system 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64
CHPL_HOME: /home/ahayashi/work/test/chapel *
script location: /home/ahayashi/work/test/chapel/util/chplenv
CHPL_TARGET_PLATFORM: linux64
CHPL_TARGET_COMPILER: gnu
CHPL_TARGET_ARCH: x86_64
CHPL_TARGET_CPU: native
CHPL_LOCALE_MODEL: flat
CHPL_COMM: none
CHPL_TASKS: qthreads
CHPL_LAUNCHER: none
CHPL_TIMERS: generic
CHPL_UNWIND: none
CHPL_MEM: jemalloc
CHPL_ATOMICS: cstdlib
CHPL_GMP: none
CHPL_HWLOC: hwloc
CHPL_REGEXP: none
CHPL_LLVM: none
CHPL_AUX_FILESYS: none
$ make -j
$ cd ../
$ git clone https://github.com/ahayashi/chapel-gpu.git
$ ls
chapel  chapel-gpu
$ cd chapel-gpu/apps/vector_copy
$ make cudagpu
$ make cudahybrid
```
